### ISSUE TITLE
Unable to update native packages

### ISSUE THREAD

**Issue by iladan** [NuGet/NuGet.CommandLine#10]
Having a C++ project which is using nuget package CppNative.1.0.0.0.nupkg targeting framework "native". Packages.config looks like:

   package id="CppNative" version="1.0.0.0" targetFramework="Native" 

Runing _nuget.exe update CppNative SolutionName.sln_ 
Result (using nuget.exe of version 2.8.5): 
WARNING: Could not install package 'CppNative 2.0.0.60'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Problem:**
Package is not updated, but removed.

**Comment by deepakaravindr** [comment]
This bug has been moved to https://github.com/NuGet/Home/issues/1291

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
