### ISSUE TITLE
NuGet - push with a fully-qualified path on POSIX fails.

### ISSUE THREAD

**Issue by dmccaffery** [NuGet/NuGet.CommandLine#11]
When executing NuGet pack command using a fully-qualified path to the nupkg (such as Linux or Mac), NuGet is incorrectly assuming that the specified path is relative to the current directory.

For instance:

If pwd = /Volumes/Storage/Users/test/repos/nuget

dnx nuget.exe push "/Volumes/Storage/users/test/repos/nuget/packages/test.pkg" -Source "/Volumes/Storage/Users/test/.config/NuGet/packages"

fails with error message:

Directory '/Volumes/Storage/Users/test/repos/nuget/Volumes/Storage/Users/test/repos/nuget/packages' not found.

**Comment by deepakaravindr** [comment]
This issue has been moved to https://github.com/NuGet/Home/issues/1289

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
