### ISSUE TITLE
2.8.6 doesn't work on .NET 4.0

### ISSUE THREAD

**Issue by zapov** [NuGet/NuGet.CommandLine#12]
>..\NuGet.exe Pack Project.nuspec
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 2.8.5.
Updating NuGet.exe to 2.8.6.
Update successful.
Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from as
sembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e
089'.

**Comment by deepakaravindr** [comment]
This bug has been moved to https://github.com/NuGet/Home/issues/1287

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
