### ISSUE TITLE
Wrong markdown for usage examples

### ISSUE THREAD

**Issue by skazantsev** [NuGet/NuGet.CommandLine#13]
The help command generates a blockquote only for the first usage example. It looks like a bug.
The version of NuGet I use is 2.8.60717.93

*Command:*

    NuGet.exe help -All -Markdown

*Output:*
....

### Examples

    nuget install elmah

nuget install packages.config

nuget install ninject -o c:\foo

....

**Comment by deepakaravindr** [comment]
This bug has been moved to https://github.com/NuGet/Home/issues/1285

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
