### ISSUE TITLE
Support -ExcludeVersion for Restore and Update commands

### ISSUE THREAD

**Issue by KorsG** [NuGet/NuGet.CommandLine#14]
Hi,

Would it be possible to implement the -ExcludeVersion option for Restore and Update commands, just like the Install command ?

**Comment by deepakaravindr** [comment]
This bug has been moved to https://github.com/NuGet/Home/issues/1286

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
