### ISSUE TITLE
Unable to download packages from NuGet official package source when use protocolVersion 2 and 3 simultaneously  in nuget.config

### ISSUE THREAD

**Issue by StasPerekrestov** [NuGet/NuGet.CommandLine#15]
Unable to download packages from NuGet official package source

Steps to reproduce:
1. Use protocolVersion="3" for NuGet official package source in nuget.config
```xml 
<add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
```
2. Add own repository 
```xml 
<add key="My nuget repository" value="http://nuget.myserver.com/nuget/" />
```
3. Remove packages folder
4. Clean %AppData%\..\Local\NuGet\Cache

Result:
Nuget.exe doesn't download packages from the official source

**Comment by deepakaravindr** [comment]
The issue has been moved to https://github.com/NuGet/Home/issues/1283

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
