### ISSUE TITLE
Does not work with MSBuild 14

### ISSUE THREAD

**Issue by twenzel** [NuGet/NuGet.CommandLine#16]
The NuGet (commandline) client does not work with MSBuild 14.
The Nuget Code relies on the internal class "Microsoft.Build.Construction.SolutionParser" wich does not exists in MSBuild 14.

Please provide a fix/workaround.

**Comment by deepakaravindr** [comment]
Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon. But, the beta version should work with MSBuild 14
