### ISSUE TITLE
automatic package restore to run init.ps1 scripts after restoring

### ISSUE THREAD

**Issue by MarkusWild** [NuGet/NuGet.CommandLine#19]
Hi,

I have seen this issue already on codeplex but it seems to be lost or abandoned. Are there any activities around running init.ps1on Package restore?

Are there reasons not to do it?

Markus

**Comment by deepakaravindr** [comment]
This issue has been moved to https://github.com/NuGet/Home/issues/1292

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
