### ISSUE TITLE
Possibility to download explicit version of nuget.exe

### ISSUE THREAD

**Issue by wallymathieu** [NuGet/NuGet.CommandLine#4]
In order to write a homebrew script that installs nuget as a tool it would be nice to be able to download specific versions in order to be able to compare the exe with a hash.

A first take on a [homebrew nuget package](https://github.com/Homebrew/homebrew/compare/master...wallymathieu:nuget)

**Comment by yishaigalatzer** [comment]
We have just added this support on dist.nuget.org (starting with 3.X Beta), we will had a json document to enable querying for available versions.

You can do it today with downloading the nuget command line package from nuget.org as well.
