### ISSUE TITLE
Nuget Command does not update solution level packages

### ISSUE THREAD

**Issue by MiguelAlho** [NuGet/NuGet.CommandLine#5]
In a large solution, i have nuget restore enabled, which adds the .nuget\ folder to my solution folder. I use a couple of solution level packages that include tools used by the solution or by the build process. These packages, when added to the solution, are referenced in the .nuget\packages.config file.

I'm trying to update a specific package that is referenced in the .nuget\package.config (and therefore NOT referenced by any specific project), with a command line call. It's a package that my team generates with some application artifacts that get added in the final build. Because its added at the solution level, I was trying to run (from my solution folder):

.nuget\Nuget.exe update .nuget\packages.config

This command returns a (localized) message:

Unable to locate project file for 'C:\<path to solution>\.nuget\packages.config'.

The config file is there, so the param seems to be read correctly. This issue is similar to two that were on the codeplex issues list:

https://nuget.codeplex.com/workitem/3118
https://nuget.codeplex.com/workitem/3848

These are marked as closed, but whatever the fix, it doesn't seem to support this situation.

Also, I tried cloning this repo to run the code in debug, but there are a series of dependencies (namely Nuget.Configuration 3.0.0-beta) that can't be resolved. Any Ideas?

**Comment by deepakaravindr** [comment]
Filed https://github.com/NuGet/Home/issues/1281 to track this issue

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
