### ISSUE TITLE
Removing a package with lots of files takes ages

### ISSUE THREAD

**Issue by brgrz** [NuGet/NuGet.CommandLine#6]
We have an internal Nuget package about 3 MB in size, containing one ASP.NET MVC site area. The package holds about 600 files (mostly small, for instance CKEditor buid) in some 300 folders. 

When initiating package update from within VS, NuGet starts to remove the old version and it is this step that takes "forever" (about 10-15 minutes on a modern highend machine with SSD drive).

Once the package is removed the new version is installed pretty quickly (but still much slower than unzipping it manually).

What does the NuGet team need from me to debug this?

**Comment by deepakaravindr** [comment]
The bug has been moved to https://github.com/NuGet/Home/issues/1284

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
