### ISSUE TITLE
nuget.exe excludes *.nuspec files and there is no way to bypass this

### ISSUE THREAD

**Issue by tugberkugurlu** [NuGet/NuGet.CommandLine#7]
> Nice to see NuGet finally moving to GitHub :fireworks: 

I was trying to do ASP.NET 5 deployment with Octopus Deploy and I needed to `nuget pack` all the application stuff. This also contains the packages and their nuspec files. However, nuget.exe excludes those and there is no way to override them. There must be a good reason why this is a default behavior and I don't like to use NuGet for stuff like deploying applications but this made me write following horrible build script (this cheap trick was what I can come up with at 1 AM :smile:):

```powershell
task NuGet-Pack {
    
    ## TeamCity stuff. Get this as a parameter
    $buildNumber = $env:BUILD_NUMBER
    if($buildNumber -eq $null) 
    {
        $buildNumber = "0.9.9.9999"
    } 
    else 
    {
        # nuget.exe doesn't include nuspec files. So, zip up and pack that instead
        # but only do this on build server for now, fix this later

        if(test-7za -eq $false)
        {        
            Write-Output "Found 7za.exe. Zipping the application"
            
            $confidenceAppPath = "$artifactsAppsRoot\Confidence.Client.Web"
            7za a "$artifactsAppsRoot\app.zip" "$confidenceAppPath\*"

            $longPathPath = "$solutionRoot\packages\Pri.LongPath\lib\net40\Pri.LongPath.dll"
            [System.Reflection.Assembly]::LoadFile($longPathPath) | Out-Null
            $directoryInfo = New-Object Pri.LongPath.DirectoryInfo -argumentlist $confidenceAppPath
            $directoryInfo.Delete($true)
            New-Item $confidenceAppPath -ItemType Directory
            Move-Item -Path "$artifactsAppsRoot\app.zip" -Destination $confidenceAppPath
        }
        else 
        {
            throw "7za doesn't exists globally"
        }
    }
    
    & "$solutionRoot\.nuget\nuget.exe" pack "$solutionRoot\Confidence.Client.Web.nuspec" -OutputDirectory "$artifactsRoot" -Version $buildNumber -NoPackageAnalysis -NoDefaultExcludes
}
```

Is it possible to provide a switch like `-IKnowWhatIAmDoingGetAwayFromMyWay`? Here is the nuspec file I am using to create the NuGet package:

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>Confidence.Client.Web</id>
    <version>0.0.0</version>
    <authors>foo bar</authors>
    <owners>foo bar</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Confidence Web Client</description>
  </metadata>
<files>
  <file src="artifacts\apps\Confidence.Client.Web\**\*" />
</files>
</package>
```

**Comment by ChaseFlorell** [comment]
We're in the same boat. `.nuspec` and `.nupkg` files cannot be contained in the manifest, and this is very problematic.

Nuget has definitely expanded far beyond what they thought it could do, and so some of these philosophies need to change. For us it's also Octopus Deploy related. We're trying to bundle a WPF app built using squirrel, and we can't do it out of the box. Instead, I've been creating extensions `cepsun` and renaming them once they're unpackaged... this is far from convenient.

**Comment by tugberkugurlu** [comment]
@ChaseFlorell thinking about this more, I really think that this isn't a NuGet problem. In NuGet's domain, it makes sense to have this restriction. However, we try to **NuGet everything possible** and that's clearly wrong. This is one of the problems arises from that and there are possibly more.

**Comment by ChaseFlorell** [comment]
while you're correct, Nuget is evolving and needs to be more flexible.

**Comment by deepakaravindr** [comment]
This bug has been moved to https://github.com/NuGet/Home/issues/1290

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
