### ISSUE TITLE
cannot build head

### ISSUE THREAD

**Issue by jmecosta** [NuGet/NuGet.CommandLine#9]
nuget restore:
Unable to find version '3.0.0-beta' of package 'NuGet.Configuration
Unable to find version '3.0.0-beta' of package 'NuGet.PackageManage
Unable to find version '3.0.0-beta' of package 'NuGet.Packaging'.
Unable to find version '3.0.0-beta' of package 'NuGet.Protocol'.
Unable to find version '3.0.0-beta' of package 'NuGet.Protocol.Type
Unable to find version '3.0.0-beta' of package 'NuGet.Versioning'.

which feed contains this?

**Comment by joaomello** [comment]
I'am with the same issue, and I add "https://www.myget.org/F/nugetbuild/" but not found.

**Comment by deepakaravindr** [comment]
Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo
